source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXCalendarUtils_Example', :exclusive => true do
  pod 'BXCalendarUtils', :path => '../'
end

target 'BXCalendarUtils_Tests', :exclusive => true do
  pod 'BXCalendarUtils', :path => '../'

  
end
